# Generated by Django 6.0.1 on 2026-02-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationcode',
            old_name='attemps',
            new_name='attempts',
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
